# Generated by Django 5.2.5 on 2026-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=10),
        ),
    ]
