# Generated by Django 5.2.5 on 2026-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
