# Generated by Django 5.2.5 on 2026-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobpost_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='external_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
