# Generated by Django 5.2.5 on 2026-04-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobpost_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='hiring_type',
            field=models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], default='job', max_length=20),
        ),
    ]
